import '@/common/syles/globals.css'
import "primereact/resources/themes/lara-light-indigo/theme.css";      
import "primereact/resources/primereact.min.css";
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthStatus from '../common/components/authStatus'
import SessionProviderWrapper from '@/common/utils/sessionProviderWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <SessionProviderWrapper>
            <html lang="en">
                <body className={inter.className}>
                    <div>{children}</div>
                    <AuthStatus />
                </body>
            </html>
        </SessionProviderWrapper>
    )
}
