import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthStatus from '../components/authStatus'
import SessionProviderWrapper from '@/utils/sessionProviderWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <SessionProviderWrapper>
            <html lang="en">
                <body className={inter.className}>
                    <div>{children}</div>
                    <AuthStatus />
                </body>
            </html>
        </SessionProviderWrapper>
    )
}
